### ISSUE TITLE
遇到无法安装python3

### ISSUE THREAD

**Issue by WLH666666Wang** [DyingLight12/Android_Learning#7]
![7e751e8acdb3f737__01](https://user-images.githubusercontent.com/48315888/57999530-4ccd7980-7b08-11e9-940a-994e3838c99d.jpg)
大佬，这个怎么解决？

**Comment by klcb2010** [comment]
重新安装呗，你花圈上面有个IP是链接失败的

**Comment by WLH666666Wang** [comment]
> 重新安装呗，你花圈上面有个IP是链接失败的

好的，谢谢

**Comment by DyingLight12** [comment]
apt install python3-pip --fix-missing
